#!/bin/sh

# Script Environment Variables
# -------------------------------------------------------------------------------------
# SYNOPKG_PKGNAME				=	Package identify which is defined in INFO
# SYNOPKG_PKGVER				=	Package version which is defined in INFO
# SYNOPKG_PKGDEST				=	Package destination path
# 									/volume[x]/@appstore/[Package Name]
# SYNOPKG_TEMP_UPGRADE_FOLDER 	= 	Temporary upgrade folder
#									/volume1/@tmp/synopkg.tmp/[Package Name]
# -------------------------------------------------------------------------------------

TIMESTAMP=$(date '+%Y-%m-%d%t%H:%M:%S')

case $SYNOPKG_DSM_LANGUAGE in
	ger)
	echo "<h3 style=\"color: red;\>Wichtiger Hinweis:</h3>Ab AutoPilot Version 1.1-000 wird der Inhalt der autopilot Scriptdatei nicht mehr ausgeführt, sondern nur noch geprüft, ob sich eine leere Datei mit dem Namen autopilot auf dem externen Datenträger befindet.<br /><br />Verschiebe daher bitte den Inhalt der aktuellen autopilot Scriptdatei an einen Ort innerhalb eines freigegebenen Ordners deiner DiskStation, gib der Datei einen neuen, eindeutigen Namen und verwende als Dateiendung zwingend .sh. Lösche anschließend die autopilot Scriptdatei von dem externen Datenträger.<br /><br />Weitere Informationen erhälst du in der AutoPilot App." > $SYNOPKG_TEMP_LOGFILE
	;;
	enu)
	echo "<h3 style=\"color: red;\>Important note:</h3>As of AutoPilot version 1.1-000, the contents of the autopilot script file are no longer executed, but only checked whether there is an empty file with the name autopilot The external storage medium is located.<br /><br />Please move the contents of the current autopilot script file to a location within a shared folder on your DiskStation, give the file a new, unique name and make sure to use .sh as the file extension. Then delete it the autopilot script file from the external data carrier.<br /><br />You can find further information in the AutoPilot app." > $SYNOPKG_TEMP_LOGFILE
	;;
esac

# Backup user settings
# -------------------------------------------------------------------------------------
if [ ! -d "${SYNOPKG_TEMP_UPGRADE_FOLDER}/usersettings" ]; then
	mkdir -p -m 755 ${SYNOPKG_TEMP_UPGRADE_FOLDER}/usersettings
fi

echo ''${TIMESTAMP}' - Start package update --> '${SYNOPKG_PKGNAME}' '${SYNOPKG_PKGVER}'' >>/tmp/${SYNOPKG_PKGNAME}.history

if [ -d "${SYNOPKG_PKGDEST}/ui/usersettings" ]; then
    cp -rf ${SYNOPKG_PKGDEST}/ui/usersettings/* ${SYNOPKG_TEMP_UPGRADE_FOLDER}/usersettings
	echo ''${TIMESTAMP}' - Backup user settings from '${SYNOPKG_PKGDEST}'/ui/usersettings to '${SYNOPKG_TEMP_UPGRADE_FOLDER}'/usersettings' >>/tmp/${SYNOPKG_PKGNAME}.history
else
		echo ''${TIMESTAMP}' - Backup user settings failed' >>/tmp/${SYNOPKG_PKGNAME}.history
fi

exit 0